name: CI Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Menampilkan Daftar File
        run: ls -R

      - name: Validasi HTML
        run: |
          if [ -f index.html ]; then
            echo "index.html ditemukan"
          else
            echo "index.html tidak ditemukan"
            exit 1
          fi

      - name: Validasi CSS
        run: |
          if [ -f style.css ]; then
            echo "style.css ditemukan"
          else
            echo "style.css tidak ditemukan"
            exit 1
          fi

      - name: Validasi JavaScript
        run: |
          if [ -f script.js ]; then
            echo "script.js ditemukan"
          else
            echo "script.js tidak ditemukan"
            exit 1
          fi

      - name: Build Berhasil
        run: echo "CI Pipeline berhasil dijalankan."
